/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package freebreakout;


public class Options extends javax.swing.JFrame implements Runnable {

    Main p;
    /**
     * Creates new form Options
     */
    public Options(Main parent) {
        initComponents();
        p = parent;
        this.setLocationRelativeTo(parent);
        this.setVisible(true);
        this.toFront();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jrbSlow = new javax.swing.JRadioButton();
        jrbNormal = new javax.swing.JRadioButton();
        jrbFast = new javax.swing.JRadioButton();
        jrbExtreme = new javax.swing.JRadioButton();
        jbOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Opcje startowe");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Prędkość gry"));

        buttonGroup1.add(jrbSlow);
        jrbSlow.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbSlow.setText("Mała");

        buttonGroup1.add(jrbNormal);
        jrbNormal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbNormal.setSelected(true);
        jrbNormal.setText("Normalna");

        buttonGroup1.add(jrbFast);
        jrbFast.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbFast.setText("Wysoka");

        buttonGroup1.add(jrbExtreme);
        jrbExtreme.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbExtreme.setText("Ekstremalna");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbSlow)
                    .addComponent(jrbNormal)
                    .addComponent(jrbFast)
                    .addComponent(jrbExtreme))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbSlow, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbFast, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbExtreme, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jbOK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbOK.setText("Start!");
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
        int d = -1;
        if(jrbSlow.isSelected()) d=1;
        else if(jrbNormal.isSelected()) d=2;
        else if(jrbFast.isSelected()) d=3;
        else if(jrbExtreme.isSelected()) d=4;
        p.setDifficulty(d);
        p.start();
        this.dispose();
    }//GEN-LAST:event_jbOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbOK;
    private javax.swing.JRadioButton jrbExtreme;
    private javax.swing.JRadioButton jrbFast;
    private javax.swing.JRadioButton jrbNormal;
    private javax.swing.JRadioButton jrbSlow;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {

    }
}
